# Generated by Django 5.0.3 on 2024-03-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="highest_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="listing",
            name="highest_bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highest_bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
