# Generated by Django 4.2.11 on 2024-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='account_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
