# Generated by Django 4.2.11 on 2024-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0005_rename_name_account_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Select one', max_length=7),
            preserve_default=False,
        ),
    ]
