# Generated by Django 4.2.11 on 2024-04-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0008_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='transaction_name',
        ),
    ]
