# Generated by Django 4.2.11 on 2024-04-18 14:47

from django.db import migrations

def convert_account_names_to_foreign_keys(apps, schema_editor):
    Transaction = apps.get_model('monemome', 'Transaction')
    Account = apps.get_model('monemome', 'Account')
    for transaction in Transaction.objects.all():
        account_name = transaction.account_name
        account = Account.objects.filter(name=account_name).first()
        if account:
            transaction.account = account
            transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0008_alter_transaction_account_name'),
    ]

    operations = [
        migrations.RunPython(convert_account_names_to_foreign_keys),
    ]
