# Generated by Django 4.2.11 on 2024-04-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0009_auto_20240418_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_name',
            new_name='account',
        ),
    ]
