# Generated by Django 4.2.11 on 2024-04-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0010_alter_account_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
