# Generated by Django 4.2.11 on 2024-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0010_rename_account_name_transaction_account'),
        ('monemome', '0011_transform_account_name'),
    ]

    operations = [
    ]
