# Generated by Django 4.2.11 on 2024-04-07 19:06

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0012_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
