# Generated by Django 4.2.11 on 2024-04-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0012_merge_20240418_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value_score',
            field=models.IntegerField(choices=[(1, '1 - Low'), (2, '2'), (3, '3 - Medium'), (4, '4'), (5, '5 - High')], default=3, verbose_name='Value Score'),
        ),
    ]
