# Generated by Django 4.2.11 on 2024-04-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0013_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null='0000-00-00'),
        ),
    ]
