# Generated by Django 4.2.11 on 2024-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0014_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pre_auth_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_pre_auth',
            field=models.BooleanField(default=False, verbose_name='Pre-Auth Payment'),
        ),
    ]
