# Generated by Django 5.0.3 on 2024-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
