# Generated by Django 4.2.11 on 2024-04-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
