# Generated by Django 4.2.11 on 2024-04-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0004_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
