# Generated by Django 4.2.11 on 2024-04-16 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monemome', '0006_category_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('transaction_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('is_pre_auth', models.BooleanField(default=False, verbose_name='Pre-Authorized Payment')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring Income')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monemome.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
