# Generated by Django 4.2.11 on 2024-04-18 14:56

from django.db import migrations

def transform_account_data(apps, schema_editor):
    Transaction = apps.get_model('monemome', 'Transaction')
    Account = apps.get_model('monemome', 'Account')
    account_map = {}
    for transaction in Transaction.objects.all():
        account_name = transaction.account_name
        if account_name not in account_map:
            account, _ = Account.objects.get_or_create(name=account_name, user=transaction.user)
            account_map[account_name] = account
        transaction.account = account_map[account_name]
        transaction.save()

def reverse_transform(apps, schema_editor):
    raise RuntimeError("Cannot reverse this migration.")

class Migration(migrations.Migration):

    dependencies = [
        ('monemome', '0009_auto_20240418_1447'),
    ]

    operations = [
        migrations.RunPython(transform_account_data, reverse_code=reverse_transform),
    ]
